import { TOMATO } from './index';

export const ACTIVITY_LIST = TOMATO + 'ACTIVITY_LIST';
export const ACTIVITY_LIST_UPDATE = TOMATO + 'ACTIVITY_LIST_UPDATE';
export const ACTIVITY_LIST_ASYNC = TOMATO + 'ACTIVITY_LIST_ASYNC';
export const ACTIVITY_DETAIL = TOMATO + 'ACTIVITY_DETAIL';
export const ACTIVITY_DETAIL_BASICINFO_UPDATE = TOMATO + 'ACTIVITY_DETAIL_BASICINFO_UPDATE';
export const ACTIVITY_DETAIL_ASYNC = TOMATO + 'ACTIVITY_DETAIL_ASYNC';
export const ACTIVITY_DETAIL_DEFAULT = TOMATO + 'ACTIVITY_DETAIL_DEFAULT';
export const IS_BASIC_ACTIVITY_SAVED = TOMATO + 'IS_BASIC_ACTIVITY_SAVED';

export const REDPACKET_COLLECTION_LIST = TOMATO + 'REDPACKET_COLLECTION_LIST';
export const REDPACKET_COLLECTION_LIST_UPDATE = TOMATO + 'REDPACKET_COLLECTION_LIST_UPDATE';
export const REDPACKET_COLLECTION_LIST_ASYNC = TOMATO + 'REDPACKET_COLLECTION_LIST_ASYNC';
export const REDPACKET_COLLECTION_DETAIL = TOMATO + 'REDPACKET_COLLECTION_DETAIL';
export const REDPACKET_COLLECTION_DETAIL_BASICINFO_UPDATE = TOMATO + 'REDPACKET_COLLECTION_DETAIL_BASICINFO_UPDATE';
export const REDPACKET_COLLECTION_DETAIL_ASYNC = TOMATO + 'REDPACKET_COLLECTION_DETAIL_ASYNC';
export const REDPACKET_COLLECTION_DETAIL_DEFAULT = TOMATO + 'REDPACKET_COLLECTION_DETAIL_DEFAULT';
export const REDPACKET_COLLECTION_MUST = TOMATO + 'REDPACKET_COLLECTION_MUST';
export const REDPACKET_COLLECTION_OPTION = TOMATO + 'REDPACKET_COLLECTION_OPTION';
