/**
 * 本地菜单名称
 */
const menuInfo = [
  {
    routeName: '分析目录',
    routeUrl: '/oap/index',
    child: [],
    isMenuShow: true,
    menuCode: 3,
  },
  {
    routeName: '人群',
    routeUrl: '/imp/segment',
    child: [],
    isMenuShow: true,
    menuCode: 21,
  },
  {
    routeName: '自助取数',
    routeUrl: '/oap/home',
    child: [],
    isMenuShow: true,
    menuCode: 4,
  },
  {
    routeName: '报告数据详情',
    routeUrl: '/oap/report-data-details',
    child: [],
    isMenuShow: false,
  },
  {
    routeName: '企业报告',
    routeUrl: '/oap/companies-report',
    child: [],
    isMenuShow: true,
  },
  {
    routeName: 'BU报告',
    routeUrl: '/oap/bu-report',
    child: [],
    isMenuShow: true,
  },
  {
    routeName: '个人报告',
    routeUrl: '/oap/individual-report',
    child: [],
    isMenuShow: true,
  },
  {
    routeName: '业务大屏',
    routeUrl: '/oap/business-time',
    child: [],
    isMenuShow: true,
    menuCode: 1,
  },
  {
    routeName: '注册报告',
    routeUrl: '/oap/registration-report',
    child: [],
    isMenuShow: true,
    menuCode: 2,
  },
  {
    routeName: 'SQL查询',
    routeUrl: '/oap/sql',
    child: [],
    isMenuShow: true,
    menuCode: 5,
  },
  {
    routeName: 'MDX分析',
    routeUrl: '/oap/mdx',
    child: [],
    isMenuShow: true,
    menuCode: 6,
  },
  {
    routeName: 'Ticket Analysis',
    routeUrl: '/oap/ticketAnalysis',
    child: [],
    isMenuShow: true,
    menuCode: 7,
  },
  {
    routeName: '机器学习',
    routeUrl: '/oap/jupyter',
    child: [],
    isMenuShow: true,
    menuCode: 8,
  },
  {
    routeName: '自定义规则',
    routeUrl: '/oap/customRules',
    child: [],
    isMenuShow: true,
    menuCode: 9,
  },
  {
    routeName: '分析调度',
    routeUrl: '/oap/schedule',
    child: [],
    isMenuShow: true,
    menuCode: 10,
  },
  {
    routeName: '数据目录',
    routeUrl: '/oap/sheetDirectory',
    child: [],
    isMenuShow: true,
    menuCode: 11,
  },
  {
    routeName: '指标目录',
    routeUrl: '/oap/indexDirectory',
    child: [],
    isMenuShow: true,
    menuCode: 12,
  },
  {
    routeName: '维度目录',
    routeUrl: '/oap/dimensionDirectory',
    child: [],
    isMenuShow: true,
    menuCode: 13,
  },
  {
    routeName: '主数据',
    routeUrl: '/oap/master-data',
    child: [],
    isMenuShow: true,
    menuCode: 15,
  },
  {
    routeName: '监控看板',
    routeUrl: '/oap/public-monitor-board',
    child: [],
    isMenuShow: true,
    menuCode: 17,
  },
  {
    routeName: '数据上传',
    routeUrl: '/oap/upload-data-warehouse',
    child: [],
    isMenuShow: true,
    menuCode: 18,
  },
  {
    routeName: '产品主数据上传',
    routeUrl: '/oap/upload-main-data',
    child: [],
    isMenuShow: true,
    menuCode: 19,
  },
  {
    routeName: '报告上传',
    routeUrl: '/oap/report-upload',
    child: [],
    isMenuShow: true,
    menuCode: 20,
  },
  {
    routeName: '申请列表',
    routeUrl: '/oap/apply-auth',
    child: [],
    isMenuShow: true,
    menuCode: 16,
  },
  {
    routeName: '数仓目录',
    routeUrl: '/oap/database',
    child: [],
    isMenuShow: true,
    menuCode: 14,
  },
  {
    routeName: '数据查询',
    routeUrl: '/oap/data_query',
    child: [],
    isMenuShow: true,
  },
  {
    routeName: '报告看板',
    routeUrl: '/oap/report-board',
    child: [],
    isMenuShow: true,
    menuCode: 22,
  }
  // {
  //   routeName: 'xxxx...',
  //   routeUrl: '/oap/xxxx...',
  //   child: [],
  //   isMenuShow: true,
  // },
]

export default menuInfo;