import { MERCHANT } from './index';

export const MERCHANT_NEXT_STEP = MERCHANT + 'MERCHANT_NEXT_STEP';
export const MERCHANT_EXECUTE_ACTION = MERCHANT + 'MERCHANT_EXECUTE_ACTION';
export const SHOP_CATEGORIES = MERCHANT + 'SHOP_CATEGORIES';
export const MERCHANT_DETAIL = MERCHANT + 'MERCHANT_DETAIL';
export const SHOP_ID = MERCHANT + 'SHOP_ID';
export const ISAUCTION = MERCHANT + 'ISAUCTION';
export const MERCHANT_SELECT_SHOP = MERCHANT + 'MERCHANT_SELECT_SHOP';
export const MERCHANT_SHOW_SEQUENTIAL = MERCHANT + 'MERCHANT_SHOW_SEQUENTIAL';
export const MERCHANT_SALE_CITYS = MERCHANT + 'MERCHANT_SALE_CITYS';
export const MERCHANT_PRO_UPDATE= MERCHANT + 'MERCHANT_PRO_UPDATE';
export const MERCHANT_ONLY_VIEW= MERCHANT + 'MERCHANT_ONLY_VIEW';
export const MERCHANT_THIRDPARTIES= MERCHANT + 'THIRDPARTIES';